### ISSUE TITLE
Any plans to support annotation compatibility issues

### ISSUE THREAD

**Issue by nikhilkr123** [lvc/japi-compliance-checker#19]
Hello, 

I would like to know about the plans for supporting annotation related compatibility issues.
Is it in your near future roadmap?

**Comment by aponomarenko** [comment]
Implemented check for removed annotations in 1.4.3 version of the tool. Please check if it works for you.

Implementing of more checks for other BC issues with annotations is on my TODO list.

Thank you!

**Comment by nikhilkr123** [comment]
Thanks. Its works!!!
