### ISSUE TITLE
Not working with Java8

### ISSUE THREAD

**Issue by ndimiduk** [lvc/japi-compliance-checker#23]
I'm getting empty reports when run with Java8. Specifically, Oracle jdk1.8.0_65 on OSX and OpenJDk 1.8.0_45-internal-b14 on ubuntu. I'm afraid it's not much to do on, but I did file [HBASE-14933](https://issues.apache.org/jira/browse/HBASE-14933) for tracking any necessary changes on our end.

**Comment by ndimiduk** [comment]
This is as of commit 2ac917f.

**Comment by aponomarenko** [comment]
Hello,

Thank you for reporting the issue.

What is your Ubuntu version? I'll try to debug the tool on it.

**Comment by ndimiduk** [comment]
Hi Andrey. Thanks a lot for taking a look! That machines is ubuntu 15.04, 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.04
Release:        15.04
Codename:       vivid
$ uname -a
Linux euclid 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ java -version
openjdk version "1.8.0_45-internal"
OpenJDK Runtime Environment (build 1.8.0_45-internal-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /home/ndimiduk/Downloads/apache-maven-3.3.3
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-30-generic", arch: "amd64", family: "unix"
```

**Comment by aponomarenko** [comment]
Hello,

I've just tried the tool on the clear Ubuntu 15.04 Live x86_64 with OpenJDK-8 and all internal tests were passed:

    ]$ sudo apt-get install openjdk-8-jdk
    ]$ perl japi-compliance-checker.pl --test   
    
    verifying detectable Java library changes
    using Java 1.8.0_45-internal
    reading classes 1.0 ...
    reading classes 2.0 ...
    comparing classes ...
    creating compatibility report ...
    result: INCOMPATIBLE (Binary: 35.7%, Source: 42.9%)
    total "Binary" compatibility problems: 55, warnings: 20
    total "Source" compatibility problems: 60, warnings: 3

Could you please run

    japi-compliance-checker --test

And compare the output?

Also please check if you are using the latest version of the tool:

    japi-compliance-checker --version

If all is OK please give me the sample JARs where the tool returned empty report and I will debug the tool on them.

Meanwhile I'll try to run the tool with the Oracle's JDK.

Thank you.

**Comment by dimaspivak** [comment]
This can be closed, @aponomarenko; we've solved the underlying issue in our HBase script and I can confirm that the tool works on JDK8.

**Comment by lvc** [comment]
Good to know. Thank you!
