### ISSUE TITLE
Ignore APIs with specified annotation

### ISSUE THREAD

**Issue by andrewgaul** [lvc/japi-compliance-checker#24]
jclouds uses the Guava `@Beta` annotation to denote unstable APIs.  We would like this checker to ignore APIs with specified annotations like this.

**Comment by aponomarenko** [comment]
Hello, Andrew.

I've added `-skip-annotations-list PATH` option in the commit d83910abb7f0aee8e6b588c5d63c87a223874f2c. The `PATH` — is a path to a file with the list of annotations:

    package.annotation1
    ...
    package.annotationN

Please try it on your project.

Thank you.

**Comment by lvc** [comment]
Hello,

You need to specify a path to file with the following content to the `-skip-annotations-list` option of the tool:

    com.google.common.annotations.Beta

I've added jclouds library to upstream tracker for daily analysis: http://abi-laboratory.pro/java/tracker/timeline/jclouds-core/

See https://github.com/lvc/japi-tracker project for more info.

Thank you.
