### ISSUE TITLE
-client CLIENT.jar then met ERROR: can't find "jar" command

### ISSUE THREAD

**Issue by demonhsh** [lvc/japi-compliance-checker#25]
JDK version: Java 1.7.0_79
Perl version: v5.18.2
OS: Mac OS 10.10.4
japi-compliance-checker version: latest

Issue I met:

japi-compliance-checker -lib mylib -old V1.xml -new V2.xml
This one works fine, the report can be generated.

But when append -client like this:
japi-compliance-checker -lib mylib -old V1.xml -new V2.xml -client testClient.jar

then met error message:
ERROR: can't find "jar" command

PS: "jar" command works fine in my command window when I execute it.

Anyone met this issue?

**Comment by jpitz** [comment]
I found that by providing the -jdk-path argument resolves this

**Comment by lvc** [comment]
Hello,

Thanks for reporting the issue.

The tool requires the `jar` and `javap` commands to be available on the command line. You can set `PATH` variable properly in your `.bash_profile`:

    export PATH=$PATH:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin

Is there a method to determine the path to the default Java install tree? `/usr/libexec/java_home`?

Thank you.

**Comment by jpitz** [comment]
I know that my JAVA_HOME/bin was on the path, but for some reason it was still failing to resolve. I simply wrapped the execution and provided the jdk path argument and it appeared to resolve it fine after that.

**Comment by lvc** [comment]
Reproduced on OS X Mavericks. Fixed by the commit 6ccf0d7db2cda9c0fe4d4aa75bd5975288bcaf5e.

Thank you.
