### ISSUE TITLE
passing comma separated list of jars broken

### ISSUE THREAD

**Issue by busbey** [lvc/japi-compliance-checker#27]
looks like the change in commit e206a1d4516e5e74a3535789b0e62c79606986a5 broke the ability to pass a comma separated list of jars instead of a descriptor file.

with that change in place, when I give a list of jars I get this error:

````bash
Running the Java API Compliance Checker...
ERROR: can't access './target/compatibility/1/hbase-annotations/target/hbase-annotations-1.2.1.jar,./target/compatibility/1/hbase-checkstyle/target/hbase-checkstyle-1.2.1.jar,./target/compatibility/1/hbase-client/target/hbase-client-1.2.1.jar,./target/compatibility/1/hbase-common/target/hbase-common-1.2.1.jar,./target/compatibility/1/hbase-examples/target/hbase-examples-1.2.1.jar,./target/compatibility/1/hbase-external-blockcache/target/hbase-external-blockcache-1.2.1.jar,./target/compatibility/1/hbase-hadoop-compat/target/hbase-hadoop-compat-1.2.1.jar,./target/compatibility/1/hbase-hadoop2-compat/target/hbase-hadoop2-compat-1.2.1.jar,./target/compatibility/1/hbase-it/target/hbase-it-1.2.1.jar,./target/compatibility/1/hbase-prefix-tree/target/hbase-prefix-tree-1.2.1.jar,./target/compatibility/1/hbase-procedure/target/hbase-procedure-1.2.1.jar,./target/compatibility/1/hbase-protocol/target/hbase-protocol-1.2.1.jar,./target/compatibility/1/hbase-resource-bundle/target/hbase-resource-bundle-1.2.1.jar,./target/compatibility/1/hbase-rest/target/hbase-rest-1.2.1.jar,./target/compatibility/1/hbase-server/target/hbase-server-1.2.1.jar,./target/compatibility/1/hbase-shell/target/hbase-shell-1.2.1.jar,./target/compatibility/1/hbase-testing-util/target/hbase-testing-util-1.2.1.jar,./target/compatibility/1/hbase-thrift/target/hbase-thrift-1.2.1.jar'

````

If I go back to prior to that commit then the list of jars is properly handled.

the invocation is in [this hbase script for building the list of jars](https://github.com/apache/hbase/blob/55bb5ff7fb20a976645f26a1a8fc3e667c05b4f7/dev-support/check_compatibility.sh)

**Comment by lvc** [comment]
Hello,

Comma-separated arguments are not supported anymore (too difficult to support). Sorry for inconvenience.

Multiple jars should be passed to the tool via XML descriptor: http://lvc.github.io/japi-compliance-checker/#Adv_Usage

Supported arguments:

1. Java ARchive (*.jar)
2. XML-descriptor (VERSION.xml file):

              <version>
                  1.0
              </version>
              
              <archives>
                  /path1/to/JAR(s)/
                  /path2/to/JAR(s)/
                   ...
              </archives>

                 ...
         
3. API dump generated by -dump option

If you'd like to analyze multiple jars then you'd better to look at the https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-monitor tools based on the japi-compliance-checker.

Thank you.

**Comment by busbey** [comment]
okay, we'll get our tooling updated for the change. any chance you could update the japi-compliance-checker version to 2.0 to flag the breaking change in behavior?

**Comment by lvc** [comment]
I'll bump version to 2.0 after adding more libraries to the upstream tracker and fixing related bugs: http://abi-laboratory.pro/java/tracker/

This will make the 2.0 version more stable.

Thank you.

**Comment by busbey** [comment]
sounds good!
