### ISSUE TITLE
Annotations list isn't working

### ISSUE THREAD

**Issue by dimaspivak** [lvc/japi-compliance-checker#28]
Sometime since v1.4.3 of this tool, support for listing annotations to analyze appears to have broken. To repro, checkout the master branch of the tool and then do as follows:
* Pull down two JARs. As an example, try [hbase-server v1.1.3](http://search.maven.org/remotecontent?filepath=org/apache/hbase/hbase-server/1.1.3/hbase-server-1.1.3.jar) and [hbase-server v.1.2.0](http://search.maven.org/remotecontent?filepath=org/apache/hbase/hbase-server/1.2.0/hbase-server-1.2.0.jar).
* Run the tool between the two JARs. Verify that methods and classes are properly read.
* Now populate an annotations file. I create one that limits to Public and LimitedPrivate interfaces:
```
dspivak-MBP:javaACC dspivak$ cat list
InterfaceAudience.Public
InterfaceAudience.LimitedPrivate
```
* Re-run the tool, specifying -annotations-list to point to the file. On my machine:
```
perl japi-compliance-checker.pl -annotations-list list /Users/dspivak/Desktop/hbase-server-1.1.3.jar /Users/dspivak/Desktop/hbase-server-1.2.1.jar 
```
* The report generated shows that no methods or classes were read.

**Comment by dimaspivak** [comment]
FWIW, I did a {{git bisect}} between {{master}} and {{1.4.3}} and it singled out {{d83910abb7f0aee8e6b588c5d63c87a223874f2c}} as the faulty commit that broke annotation lists.

**Comment by lvc** [comment]
Hello,

Thank you for reporting this.

Could you please:

1. report your Java version/vendor and name/version of your OS
2. modify the list of annotations as following and re-run the tool:
    
        org.apache.hadoop.hbase.classification.InterfaceAudience.Public
        org.apache.hadoop.hbase.classification.InterfaceAudience.LimitedPrivate

3. create API.dump of one of the Jars and attach it to this bug (see also http://lvc.github.io/japi-compliance-checker/#API_Dump):

        japi-compliance-checker -l hbase-server -dump ./hbase-server-1.1.3.jar

Thank you.

**Comment by dimaspivak** [comment]
Ooh, that did it! :) I guess the convention for needing to put the canonical name of the annotation changed with that commit? Feel free to close. Thanks as always, Andrey.

**Comment by lvc** [comment]
The analysis of annotations is more accurate for now. Therefore it's necessary to provide complete type names for annotations to filter. Looks like we need to warn a user if particular annotation is not found in the library for backward compatibility.

BTW
The API tracker for HBase can be found here:

http://abi-laboratory.pro/java/tracker/timeline/hbase/
https://github.com/lvc/upstream-tracker-4j/blob/master/profile/hbase.json

Thank you.
