### ISSUE TITLE
Java 8 default interface methods not detected

### ISSUE THREAD

**Issue by manovotn** [lvc/japi-compliance-checker#29]
I came across this problem recently...

API v1 has:
* `interface FaceA`

API v2 introduces:
* `interface FaceB` with method `do()`
* interface `FaceA extends FaceB` **and adds default implementation** of `do()`

This should pose no compatibility risk because anyone implementing `FaceA` in their apps will still be able to run his with API v2 thanks to default implementation.

To give a real background I am talking about Java EE CDI spec...
* version 1.2 has [`ObserverMethod`](https://github.com/cdi-spec/cdi/blob/1.2/api/src/main/java/javax/enterprise/inject/spi/ObserverMethod.java#L36) which does not extend anything
* version 2.0-EDR2 now extends [`Prioritized`](https://github.com/cdi-spec/cdi/blob/2.0-EDR2/api/src/main/java/javax/enterprise/inject/spi/Prioritized.java) which adds a method. However `ObserverMethod` also contains a [default implementation](https://github.com/cdi-spec/cdi/blob/2.0-EDR2/api/src/main/java/javax/enterprise/inject/spi/ObserverMethod.java#L86)

This should be perfectly fine compatibility-wise so I think it is a glitch in the script?

**Comment by lvc** [comment]
Hello,

The issue has been fixed by the commit 94320fd95c1b2248a81fbd15566c5ec2c46e0da4. Please check if it works for you.

The library has been added to the tracker: http://abi-laboratory.pro/java/tracker/timeline/cdi-api/

Thank you.

**Comment by manovotn** [comment]
That was a lightning speed fix and indeed works as expected - thanks a lot!
By the way, in the tracker (http://abi-laboratory.pro/java/tracker/timeline/cdi-api/), could you also add the SP versions of CDI 1.0 releases? 
That is, all of the following versions should be included: 1.0, 1.0-SP1, 1.0-SP2, 1.0-SP3, 1.0-SP4, 1.1, 1.2, 2.0.Alpha4 (latest 2.0)

**Comment by lvc** [comment]
Done: http://abi-laboratory.pro/java/tracker/timeline/cdi-api/

The report is intended to show changes in the public part of the API only. Please check the report and let me know if there are some false positives or negatives in the report.

Thank you.

**Comment by manovotn** [comment]
Thanks for adding it!
As for false positives - that depends on a point of view. As for a CDI user, it is nothing he will stumble upon as those classes are not to be implemented by users.
CDI integrators (Wildfly/Glassfish/..) plus CDI implementations themselves (Weld/OWB) will need to comfort to these changes anyway. So probably it is just false positive (WDYT @mkouba)

@lvc Is there a way to exclude some classes from compatibility check or to explicitly say that it is intended? If so, we might think about adding this API check as an automated step into our builds.

**Comment by lvc** [comment]
Particular classes and packages can be excluded from the analysis with the help of `-skip-internal-types REGEXP` and `-skip-internal-packages REGEXP` or with the help of `-skip-classes LIST_PATH` and `-skip-packages LIST_PATH` options.

Deprecated classes and methods can be skipped by the `-skip-deprecated` option. Annotated classes and methods can be excluded by the `-skip-annotations-list LIST_PATH` or `-annotations-list LIST_PATH` options.

Please update to 15b93d818ff9f41bc5abd6b8a7f5df7326ce38db. I've just fixed a serious problem in the code related to your issue.

Thank you.
