### ISSUE TITLE
Critical issue on Windows platform

### ISSUE THREAD

**Issue by bvarnai** [lvc/japi-compliance-checker#30]
`readClasses` gets paths without ending with .class (`readArchive` removes .class extension). On Windows javap returns an empty output and disassembling fails. I attached the logs for both cases [bad.log](https://github.com/lvc/japi-compliance-checker/files/343137/bad.txt) and [good.log](https://github.com/lvc/japi-compliance-checker/files/343141/good.txt). Dirty fix by patching `readClasses` with `my $Input = join(".class ", @{$Paths});`.
The biggest problem is that the tool gives false negative and reports 100% compatibility.

I'm using the latest version 1.7.

**Comment by lvc** [comment]
Hello,

The issue has been fixed by the commit a28753da444a5cd891a6d467f2ae0539b9e3e797.

Thank you.

**Comment by bvarnai** [comment]
Verified. Works on Windows 7. Thanks!
