### ISSUE TITLE
Undefined subroute exitStatus

### ISSUE THREAD

**Issue by amai2012** [lvc/japi-compliance-checker#35]
Running b3cf4da results in an _Undefined subroutine exitStatus_ error. Is it my fault or should current version not be used for testing?

**Comment by lvc** [comment]
Hi,

Did you installed the tool by "make install" command?

Thank you.

**Comment by amai2012** [comment]
No :-(
The previous version used to work w/o install. Need to check again.

**Comment by amai2012** [comment]
I think previous versions used to be a stand-alone .pl file, while nowadays modules are required, etc.
I am using the tool from within a job which was just downloading a single file and run the script. Now I need to install in one place and prepare a suitable collection of files to download. Less convenient, but no showstopper.
