### ISSUE TITLE
False report of binary incompatibility when generifying method

### ISSUE THREAD

**Issue by PhilippWendler** [lvc/japi-compliance-checker#38]
I have the following class:

    public abstract Foo {
      Foo() {}

      public abstract Foo doSomething();

      public static Foo create() {
        return new SomePrivateSubclassOfFoo();
      }
    }

When I change it to the following, japi-compliance-checker 2.0 claims binary incompatibility because it says `Foo doSomething()` got removed and `T doSomething()` got added:

    public abstract Foo<T extends Foo<T>> {
      Foo() {}

      public abstract T doSomething();

      public static Foo<?> create() {
        return new SomePrivateSubclassOfFoo();
      }
    }

However, because the erasure of `T` is `Foo`, this is binary compatible as explained [here](http://stackoverflow.com/a/42202329/396730).

**Comment by lvc** [comment]
Hi,

This is fixed by the commit 9d78fb028752b905326eb67f9748ff1646102746 in master. It will be a part of the release `2.2`.

Please verify it.

Thank you.

**Comment by PhilippWendler** [comment]
I can confirm it works for our project.
