### ISSUE TITLE
annotation-based filtering not removing classes as expected

### ISSUE THREAD

**Issue by busbey** [lvc/japi-compliance-checker#40]
I have an example run using the 2.1 release that is showing incompatible changes for a class that I believe should be filtered out.

I'm checking on the compatibility of change [b8ad9b1 in hbase](https://github.com/apache/hbase/commit/b8ad9b17bb6365026036687a47b3586958596d68). Note that the only change is to a class with the annotation InterfaceAudience.Private.

Here's how I'm invoking things, which I believe should restrict checking to just classes marked with InterfaceAudience.Public and InterfaceAudience.LimitedPrivate:

    $ perl ./target/java-acc/japi-compliance-checker.pl -version
    Java API Compliance Checker (JAPICC) 2.1
    
    $ perl target/java-acc/japi-compliance-checker.pl -l hbase -d1 target/compat-check/src.xml \
    -d2 target/compat-check/dst.xml -report-path target/compat-check/report.html \
    -annotations-list target/compat-check/annotations.txt \
    -skip-annotations-list target/compat-check/skip_annotations.txt

    $ cat target/compat-check/annotations.txt 
    org.apache.hadoop.hbase.classification.InterfaceAudience.Public
    org.apache.hadoop.hbase.classification.InterfaceAudience.LimitedPrivate

    $ cat target/compat-check/skip_annotations.txt
    org.apache.hadoop.hbase.classification.InterfaceAudience.Private

The [resultant report shows incompatible changes to the class from the commit](http://people.apache.org/~busbey/hbase/japi-compliance-checker-example/report.html).

**Comment by lvc** [comment]
Hi,

This is fixed by the commit b9d2fde5d864bc350ac942d42830cd4952e3bba8.

Please try new version.

Thank you.

**Comment by saintstack** [comment]
I tried 2.3 asking it to filter out  InterfaceAudience.LimitedPrivate against same code base as @busbey was using and the new version seems to do the right thing; I only see classes absent the  InterfaceAudience.LimitedPrivate annotation. Thanks.
