### ISSUE TITLE
Java 8 compatibility

### ISSUE THREAD

**Issue by ebourg** [lvc/japi-compliance-checker#9]
Hi,

I have the following error when using japi-compliance-checker with OpenJDK 8:

    ebourg@icare:~/japi-compliance-checker$ ./japi-compliance-checker.pl -test

    verifying detectable Java library changes
    reading classes 1.0 ...
    ERROR: internal error - can't read method signature

Also, the output of `java -version` changed in OpenJDK 8 and the regexp detecting the version used has to be updated:

    if(my $JavaCmd = get_CmdPath("java"))
    {
        if(my $Ver = `$JavaCmd -version 2>&1`)
        {
            if($Ver=~/(java|openjdk) version "(.+)\"/) {
                printMsg("INFO", "Using Java $2");
            }
        }
    }

Unfortunately this doesn't solve the issue mentioned above.

**Comment by KostyaSha** [comment]
@aponomarenko hi, any updates on this topic?

**Comment by lvc** [comment]
The issue has been fixed by the commit 9499535a75c77f41dbe882668483985009b79797

Thanks to all!

**Comment by aponomarenko** [comment]
The issue has been fixed by the commit 9499535a75c77f41dbe882668483985009b79797

Thanks to all!
